services:
  auth_service:
    container_name: AuthService
    build:
      context: .
      dockerfile: authorization_service/dockerfile
    ports:
      - "15432:15432"
      # - "40001:40001"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=0000
      - DB_NAME=grpc_auth_db
      - GRPC_PORT=15432
      - GRPC_TIMEOUT=24h
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    networks:
      - grpc_network
      - db_network
        
  
  db:
    container_name: postgres_db
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=grpc_auth_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:  # Ждем, пока БД будет готова
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    networks:
      - db_network

  migrator:
    container_name: migrator
    build:
      context: ./db
      dockerfile: dockerfile
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=0000
      - DB_NAME=grpc_auth_db
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - db_network
    

volumes:
  db_data:

# Before start create a network with command
# docker network create grpc_network
networks:
  grpc_network:
    external: true
  db_network:
    driver: bridge