FROM golang:1.24

WORKDIR /app/authorization_service

COPY authorization_service/ .

RUN go mod download

RUN go build -o app ./cmd/main.go

CMD ["./app"]

# FROM golang:1.24

# WORKDIR /app/authorization_service

# COPY authorization_service/ .

# RUN go mod download

# RUN go install github.com/go-delve/delve/cmd/dlv@latest

# RUN go build -gcflags="all=-N -l" -o app ./cmd/main.go

# EXPOSE 40001

# CMD ["dlv", "exec", "./app", "--headless", "--listen=:40001", "--api-version=2", "--accept-multiclient"]
